a= int(input("enter a value 0_0 "))
b= int(input("enter b value 0_0 "))
print("sum:",a+b)
print("sub:",a-b)
print("mul:",a*b)
print("div:",a/b)
print("mod:",a%b)
print("exponent:",a**b)
print("+ floor div: ",a//b)
print("- floor div:",a//b)
print("********************************************")
a= int(input("enter a value 0_0 "))
b= int(input("enter b value 0_0 "))
print("less than:",a<b)
print("greater than:",a>b)
print("less than or equal:",a<=b)
print("greater or equal:",a>=b)
print("equal to:",a==b)
print("not equal to:",a!=b)
